name: 'sample_ecommerce_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  mart:
    +materialized: table
  staging:
    +materialized: view

vars:
  start_date: '20201201'
  end_date: '20201201'
  event_level_abandon_threshold: 1800
  session_level_abandon_threshold: 21600
  basket_event_list:         
    - 'add_to_cart'
    - 'begin_checkout'
    - 'purchase'
    - 'select_item'
    - 'select_promotion'
    - 'view_item'
    - 'view_item_list'
    - 'view_promotion'